[package]
name = "block_graph"
version = "0.1.0"
edition = "2021"
rust-version = "1.85.0"
readme = "README.md"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }


[dependencies]
bitcoin = { version = "0.32", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }

[features]
default = ["std", "serde"]
std = ["bitcoin/std", "bitcoin/serde"]
serde = ["dep:serde"]

[dev-dependencies.block_graph]
path = "."
default-features = true

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "apply_update"
harness = false

[[bench]]
name = "from_changeset"
harness = false

[[bench]]
name = "is_block_in_chain"
harness = false

[[bench]]
name = "reorg"
harness = false
