name: Rust

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  STABLE: "1.98.0"
  NIGHTLY: "nightly-2026-08-01"
  MSRV: "1.85.0"

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.NIGHTLY }}
          components: rustfmt
      - run: cargo fmt --all -- --check

  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.STABLE }}
          components: clippy
      - name: cargo check
        run: cargo check --workspace --all-targets --all-features
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.STABLE }}
      - run: cargo build --workspace --all-targets --all-features

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.STABLE }}
      - run: cargo test -p block_graph --no-fail-fast --all-features --lib --

  no-std:
    name: no_std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.STABLE }}
      - run: cargo check -p block_graph --lib --no-default-features

  msrv:
    name: msrv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.MSRV }}
      - run: cargo check --workspace --all-targets --all-features
